### ISSUE TITLE
Issue with ABMA_teachersGuide.pdf

### ISSUE THREAD

**Issue by drocks13** [ABMArchaeologists/ABMA_website#1]
Downloaded the files from the website but it appears the ABMA_teachersGuide.pdf is corrupted. Tried different browsers. I think it is the source. Probably just needs a fresh copy added.

**Comment by RonaldVisser** [comment]
Corrected! Error was in the upload at Zenodo, new version uploaded there: https://doi.org/10.5281/zenodo.10980488

see commit: https://github.com/ABMArchaeologists/ABMA_website/commit/7319475d60ca4f435e3e7af0ac9673afee724ea1
